# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6b368814e40f98a287447a54d70f334521f36a9d29c845d857b5393f5faac71d5b03082f533b3466d26b5d9f732cb4dfcab26916b6d8ac5072c846491394461

test:
  secret_key_base: e467b33d4ad626359cf9598d731437dd9930099e01ebd3442347517f84f0592410c3549c048b3b4137ebb7957e90da11a48eb1d76b94df6ade9be623f7ba58f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
